### ISSUE TITLE
Leadins - device: Lead-ins image did not fit to its container

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Cafe-Del-Pescatore#121]
Affected device(s): S4 and ipodtouch5 (landscape view)

![image](https://cloud.githubusercontent.com/assets/12888048/11708341/4729b686-9f49-11e5-9b0d-73c2d2eff80e.png)

**Comment by ankittitan** [comment]
Working fine on ipodtouch5 and s4
![img_0955](https://cloud.githubusercontent.com/assets/14210977/11744681/5799b6fc-a038-11e5-9cfd-02f5ed2e46c6.PNG)
