### ISSUE TITLE
Header: Dimmi Booking Button wasn't implemented

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Cafe-Del-Pescatore#24]
![image](https://cloud.githubusercontent.com/assets/12888048/11055684/83091ebe-87b4-11e5-99bb-77c8448b673f.png)
![image](https://cloud.githubusercontent.com/assets/12888048/11055686/85ae466c-87b4-11e5-9aa4-3cf2abf525c2.png)

**Comment by romatitan** [comment]
Need feedback for this.

**Comment by ankittitan** [comment]
The script provided for Dimmy Book button is not working

**Comment by romatitan** [comment]
Then, try to find ways for the book button to work and/or clarify this with the PM as well.

**Comment by ankittitan** [comment]
Hi, the script for Dimmy button is not working and the issue is raised with Jolene and Ricky, waiitng for their reply.
![dimmi button](https://cloud.githubusercontent.com/assets/14210977/11774803/2510753a-a25f-11e5-9688-57ef3d7bdd79.png)
