### ISSUE TITLE
Clarification - Homepage magazine section: Should we limit the Find Us repeater to 2 items only? What if, the user or client wants to have an additional item?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Cafe-Del-Pescatore#55]
![image](https://cloud.githubusercontent.com/assets/12888048/11083576/b365d95a-886b-11e5-89b0-469fc7488124.png)

**Comment by suniltitan** [comment]
As per the design there are only two items shown, that is the reason it has been limited to  two items only.
