### ISSUE TITLE
Pre-Footer - device: The navigation arrow is missing

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Cafe-Del-Pescatore#88]
Affected device(s): S4, iPodtouch5

Portrait view
![image](https://cloud.githubusercontent.com/assets/12888048/11523588/6e4e3166-98fe-11e5-9f35-af3a40b71bd5.png)

Landscape view
![image](https://cloud.githubusercontent.com/assets/12888048/11523508/c5835b56-98fd-11e5-8486-6ab778a5343d.png)

**Comment by ankittitan** [comment]
Navigation arrows has been removed from mobile devices as they are too large to fit in mobile devices.
